language: cpp
compiler:
  - clang
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev libboost-graph-dev libqt4-dev qt4-qmake
# Compiling:
script: mkdir build && cd build && cmake -DCOMPILER=clang -DCMAKE_BUILD_TYPE=Release -DNO_BOOST_GRAPH=1 .. && make && cd ..
